# Generated by Django 5.1.7 on 2025-03-08 18:41

from django.db import migrations
from django.db.models import F

def create_default_profiles(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    Profile = apps.get_model('users', 'Profile')
    Invoice = apps.get_model('invoices', 'Invoice')

    # Create default profile for each user from their existing details
    for user in CustomUser.objects.all():
        # Only create if user doesn't have any profiles yet
        if not Profile.objects.filter(user=user).exists():
            # Get a display name for the business
            display_name = user.company_name
            if not display_name:
                display_name = f"{user.first_name} {user.last_name}".strip() or user.username
                display_name = f"{display_name}'s Business"

            profile = Profile.objects.create(
                user=user,
                is_active=True,  # Make this the active profile
                company_name=user.company_name or display_name,
                company_email=user.company_email or user.email,
                phone_number=user.phone_number or '',
                address=user.address or ''
            )
            
            # Link all existing invoices of this user to their default profile
            Invoice.objects.filter(user=user, profile__isnull=True).update(profile=profile)

def reverse_default_profiles(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    Invoice = apps.get_model('invoices', 'Invoice')
    
    # Remove profile references from invoices
    Invoice.objects.all().update(profile=None)
    
    # Delete all profiles
    Profile.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
        ('invoices', '0005_invoice_profile'),  
    ]

    operations = [
        migrations.RunPython(create_default_profiles, reverse_default_profiles),
    ]
