# Generated by Django 5.0.4 on 2025-03-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_default_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
