# Generated by Django 5.0.4 on 2025-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_city_profile_country_profile_gst_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin_or_zip',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
