# Generated by Django 5.1.7 on 2025-03-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
