# Generated by Django 5.1.7 on 2025-03-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(editable=False, max_length=19, unique=True),
        ),
    ]
