# Generated by Django 5.1.7 on 2025-03-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='description',
            new_name='item',
        ),
    ]
