# Generated by Django 5.0.4 on 2025-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_rename_description_invoiceitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
