# Generated by Django 5.0.4 on 2025-03-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_gst_rate_invoice_subtotal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('AUD', 'AUD'), ('CAD', 'CAD')], default='USD', max_length=3),
        ),
    ]
