# Generated by Django 5.0.4 on 2025-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_contact',
            field=models.CharField(default='0000000000', help_text='Numeric contact number (max 10 digits)', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_zip',
            field=models.CharField(blank=True, help_text='Postal/Zip code', max_length=7),
        ),
    ]
