# Generated by Django 5.0.4 on 2025-04-04 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoiceitem_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoices.invoiceitem')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
