# Generated by Django 5.0.4 on 2025-04-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_contact', models.CharField(default='0000000000', help_text='Numeric contact number (max 10 digits)', max_length=10)),
                ('customer_country', models.CharField(blank=True, max_length=50)),
                ('customer_zip', models.CharField(blank=True, help_text='Postal/Zip code', max_length=7)),
                ('customer_state', models.CharField(blank=True, max_length=50)),
                ('customer_city', models.CharField(blank=True, max_length=50)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to='invoices.invoice')),
            ],
        ),
    ]
