# Generated by Django 5.0.4 on 2025-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoicecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoicecustomer',
            name='customer_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
