# Generated by Django 5.0.4 on 2025-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoice_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
