# Generated by Django 5.0.4 on 2025-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_alter_invoice_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
