# Generated by Django 5.0.4 on 2025-04-23 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_invoicecustomer_customeuser_id_and_more'),
        ('users', '0007_alter_profile_country_alter_profile_pin_or_zip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='customuser',
            field=models.ForeignKey(blank=True, db_column='customuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='userprofile',
            field=models.ForeignKey(blank=True, db_column='userprofile_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='customuser',
            field=models.ForeignKey(blank=True, db_column='customuser_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='userprofile',
            field=models.ForeignKey(blank=True, db_column='userprofile_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile'),
        ),
    ]
